---
- hosts: localhost
  connection: local
  pre_tasks:
  - name: "Checking host file"
    stat:
      path: ./host
    register: output
  roles:
    - { role: create_instances, when: not output.stat.exists  }
