- name: Install required packages for k8
  apt:
    pkg: '{{item}}'
    state: present
    update_cache: yes
  become: yes
  with_items:
    - apt-transport-https
    - docker.io
    - git

- name: Ensuring previous clone isn't present
  file:
    state: absent
    path: '/home/ubuntu/k8-clusterConfig'

- name: Cloning Github repo
  git: repo=https://github.com/arun5493/k8-clusterConfig.git clone=yes dest=/home/ubuntu/k8-clusterConfig

- name: Start and enable docker
  systemd: state=started name=docker
  become: yes

- name: Enable docker
  systemd: enabled=yes name=docker
  become: yes

- name: get key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Create sources.list.d file for Kubernetes
  copy:
    content: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    dest: /etc/apt/sources.list.d/kubernetes.list
    force: yes

- name: Install Kubernetes applications
  apt:
    pkg: '{{item}}'
    state: present
    update_cache: yes
  become: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
