- name: Initialize cluster Networking
  shell: kubectl apply -n kube-system -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 |tr -d '\n')"

- name: Log into DockerHub
  docker_login:
    username: arun5493
    password: NCSU1wolf#
    email: ajagana@ncsu.edu
  become: yes

- name: Build a docker image using Dockerfile
  shell: docker build -t arun5493/newcheckbox .
  args:
    chdir: "/home/ubuntu/k8-clusterConfig/"
  become: yes

- name: Pull the checkbox image
  docker_image:
    name: arun5493/newcheckbox
    pull: yes
  become: yes

- name: Push the checkbox image
  docker_image:
    name: arun5493/newcheckbox
    repository: arun5493/newcheckbox
    push: yes
  become: yes

- name: Wait for two minutes for the replicas to be created and assigned
  pause:
    minutes: 2
# Do we need this step?
# - name: Running Docker image
#   shell: docker run arun5493/checkbox --env-file env.txt -p 80:80 -d arun5493/checkbox
#   args:
#     chdir: "/home/ubuntu/k8-clusterConfig/"
#   become: yes

- name: Creating a deployement with 2 replicas using the image arun5493/checkbox
  shell: kubectl run checkbox1 --image=arun5493/newcheckbox --port=80 --replicas=2

- name: Wait for two minutes for the replicas to be created and assigned
  pause:
    minutes: 2

- name: Exposing the checkbox deployment using NodePort
  shell: kubectl expose deployment checkbox1 --type=NodePort

- name: Wait for a minute for to assign NodePort
  pause:
    minutes: 1

- name: Printing the NodePort to access the application
  shell: kubectl describe services/checkbox1
  register: samp
- debug:
    var: samp
