- name: Initialize cluster Networking
  shell: kubectl apply -n kube-system -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 |tr -d '\n')"

- name: Log into DockerHub
  docker_login:
    username: "{{docker_username}}"
    password: "{{docker_password}}"
    email: "{{docker_email}}"
  become: yes

- name: Build a docker image using Dockerfile
  shell: "docker build -t {{docker_image}} ."
  args:
    chdir: "/home/ubuntu/k8-clusterConfig/"
  become: yes

- name: Pull the checkbox image
  docker_image:
    name: "{{docker_image}}"
    pull: yes
  become: yes

- name: Push the checkbox image
  docker_image:
    name: "{{docker_image}}"
    repository: arun5493/checkbox
    push: yes
  become: yes

- name: Wait for two minutes for the replicas to be created and assigned
  pause:
    minutes: 2

- name: Creating a deployement with 3 replicas using the image arun5493/newkubercheckbox
  shell: "kubectl run checkbox --image=arun5493/checkbox --port=80 --replicas=3 --env=\"MONGO_PORT=\"{{mongo_port}}\"\" --env=\"MONGO_IP=\"{{ hostvars[groups['k8.master'][0]].ansible_host }}\"\" --env=\"MONGO_USER=\"{{mongo_user}}\"\" --env=\"MONGO_PASSWORD=\"{{mongo_password}}\"\" --env=\"MAIL_USER=\"{{mail_user}}\"\" --env=\"MAIL_PASSWORD=\"{{mail_password}}\"\" --env=\"MAIL_SMTP=\"{{mail_smtp}}\"\" --env=\"checkbox_path=\"{{checkbox_path}}\"\""

- name: Wait for two minutes for the replicas to be created and assigned
  pause:
    minutes: 2

- name: Exposing the checkbox deployment using NodePort
  shell: kubectl expose deployment checkbox --type=NodePort

- name: Wait for a minute for to assign NodePort
  pause:
    minutes: 1

- name: Printing the NodePort to access the application
  shell: kubectl describe services/checkbox
  register: samp
- debug:
    var: samp.stdout_lines
